name: Run unit test
on:
  pull_request:
    branches:
      - 'master'
    types: [opened, ready_for_review, synchronize]

jobs:
  run_unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup_github_token
        run: ./script/setup-github-token.sh

      - name: run_unit_test
        run: |
          ./script/install-flutter.sh




